version: 2
updates:
    - package-ecosystem: "cargo"
      directory: "/"
      schedule:
          interval: "weekly"
          time: "08:00"
          timezone: "UTC"
      target-branch: "main"
      open-pull-requests-limit: 10
      assignees:
        - "deniskore"
