[package]
name = "iptools"
version = "0.2.2"
authors = ["Denis Avvakumov"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Deniskore/iptools"
homepage = "https://github.com/Deniskore"
description = """
Python iptools port for Rust
"""
keywords = ["ip", "iptools", "network"]
categories = ["algorithms", "network-programming"]
edition = "2021"

[dependencies]
regex = "1.6.0"
once_cell = "1.13.0"

[dev-dependencies]
pretty_assertions = "1.2.1"

[profile.release]
opt-level = 3
lto = true