on: [push, pull_request]

name: checks-CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.85.0
      - run: cargo check

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          targets: wasm32-unknown-unknown
      - run: cargo test
      - run: cargo check --no-default-features
      - run: cargo check --no-default-features --target wasm32-unknown-unknown
      - run: cargo check -p iptools-wasm --target wasm32-unknown-unknown
      - run: cargo test --features serde
      - run: cargo test --doc

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo clippy -- -D warnings
